[package]
org = "xlibb"
name = "pipe"
version = "1.4.2"
authors = ["xlibb"]
keywords = ["pipe"]
repository = "https://github.com/xlibb/module-pipe"
license = ["Apache-2.0"]
distribution = "2201.4.0"
icon = "icon.png"

[[platform.java11.dependency]]
path = "../native/build/libs/pipe-native-1.4.2-SNAPSHOT.jar"
